import './globals.css';

import { Inter } from 'next/font/google';

import Footer from './Footer';
import Navbar from './Navbar';
import SuperHeader from './SuperHeader';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next13 - eCommerce 🛒',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SuperHeader />
        <Navbar />

        <main className="min-h-full min-w-full overflow-x-clip px-8 py-12 md:py-16">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
