import './globals.css';

import { Inter as FontSans } from 'next/font/google';
import localFont from 'next/font/local';

import { cn } from '@/utils/cn';

import Footer from './components/layout/Footer';
import Navbar from './components/layout/Navbar';
import Providers from './components/layout/Providers';
import SuperHeader from './components/layout/SuperHeader';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

export const metadata = {
  title: 'Next13 - eCommerce 🛒',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn(
          'bg-background min-h-screen font-sans antialiased',
          fontSans.variable,
          fontHeading.variable,
        )}
      >
        <Providers>
          <SuperHeader />
          <Navbar />

          <main className="min-h-full min-w-full overflow-x-clip px-8 py-12 md:py-16">
            {children}
          </main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
