import type { Icon as LucideIcon } from 'lucide-react';
import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CreditCard,
  Crop,
  DollarSign,
  Download,
  Loader2,
  Moon,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SunMedium,
  Trash,
  User,
  Wallet,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronUpDown: ChevronsUpDown,
  trash: Trash,
  user: User,
  wallet: Wallet,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  shirt: Shirt,
  download: Download,
  dollarSign: DollarSign,
  crop: Crop,
  creditCard: CreditCard,
  circle: Circle,
};
